### ISSUE TITLE
"set valence,1 or off " invalid

### ISSUE THREAD

**Issue by SynchronyML** [schrodinger/pymol-open-source#188] opened 2021-06-27 05:34 UTC

**Comment by JarrettSJohnson** [comment] 2021-07-07 17:33
Can you provide a little bit more detail? I don't see an error for
`set valence, 1`

nor 

`set valence, off`

**Comment by JarrettSJohnson** [comment] 2021-12-03 17:48
Closing this issue since I cannot reproduce. Feel free to re-open if you are still experiencing this issue.

**Closed by JarrettSJohnson** 2021-12-03 17:48 UTC
