### ISSUE TITLE
OpenVR problems

### ISSUE THREAD

**Issue by JtheBAB** [schrodinger/pymol-open-source#185] opened 2021-06-05 14:14 UTC
Dear all

Thanks to Christoph Gohlke there is now a precompiled pymol version with active openVR. SteamVR recognize it but the screen is just black on my Oculus Quest 2. As ChimeraX is working perfectly it looks like PyMol isn't fully compatible with SteamVR in 2021.

Christoph mention that the openvr-1.0.x is quite old. Perhaps this is the problem? Any chance that openVR gets updated?

Thank you and best wishes

**Comment by cgohlke** [comment] 2021-06-05 16:40
Some context: the builds are using pymol-open-source-2.5.0 with [openvr-1.0.17](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.17) and Visual Studio 2017. Binaries are available at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pymol-open-source. I tried several recent versions of the openvr SDK and ran into compile errors due to API changes. 

I don't have any hardware for testing. Do the  [openvr-1.0.17 examples](https://github.com/ValveSoftware/openvr/releases/tag/v1.0.17) work with Oculus Quest 2? There's an issue at https://github.com/ValveSoftware/openvr/issues/1556 that mentions black screens on Oculus Quest 2.

Maybe the authors of PR #54 have an idea? @paulsmirnov

**Comment by JtheBAB** [comment] 2021-06-05 19:27
Ah good to know that it could also be due to the Quest 2. By the end of the week i should have a HTC Vive Pro 2 Setup to compare.

**Comment by paulsmirnov** [comment] 2021-06-07 09:21
@cgohlke We authored this PR with the original HTC Vive as the only available hardware, unfortunately. Right now I don't even have this hardware to test or suggest improvements, sorry.

**Comment by TstewDev** [comment] 2021-06-07 14:23
I have an Oculus Quest 2 and steamVR on my personal computer so I should be able to test this next week. I'll let you know if I can reproduce and/or if I can come up with an easy fix.

**Comment by TstewDev** [comment] 2021-06-21 14:07
I just tested the Quest 2 with a fresh installation of 2.5 from [pymol.org](https://pymol.org/2/) (I can test with open-source from this repo as well but this was easier to start with). I was able to view a structure without issue. I will note that I was connected to my computer through the USB-C Link cord and using Oculus Link. I opened PyMOL, loaded a structure from my computer, then accessed the OpenVR display mode from the headset using the Virtual Desktop. There may still be some issues with the controls but this seems like a separate issue if you weren't even able to view a structure. @JtheBAB Can you tell me about your set up so I can try to reproduce the same conditions?

**Comment by JtheBAB** [comment] 2021-06-21 14:18
I used the open-source file from @cgohlke. 

- Python 3.9
- pymol-2.5.0+openvr-cp39-cp39-win_amd64
- numpy-1.20.1+mkl-cp39-cp39-win_amd64
- Pmw-2.0.1-py3-none-any
- pymol_launcher-2.1-cp39-cp39-win_amd64
- pyqt5

The Oculus is linked by AirLink (ChimeraX is working). I start Steam and SteamVR. Then Pymol and load a molecule. Then i start Display --> StereoMode --> openVR

The Quest 2 is then just black.

**Comment by TstewDev** [comment] 2021-06-21 14:20
Can you try restarting SteamVR while looking at the final black screen?

**Comment by TstewDev** [comment] 2021-06-21 17:37
I downloaded and used the open-source file from @cgohlke (pymol-2.5.0+openvr-cp39-cp39-win_amd64.whl) and was able to view the structure using SteamVR. I did this with a new environment and only installed what was listed above. I think the only difference remaining is that I'm still using USB-C and Oculus Link rather than AirLink (which I will test next).

**Comment by TstewDev** [comment] 2021-06-21 18:11
Just got AirLink working and I'm able to view the structure with that as well. However, the controllers still don't seem to be working properly even though it appears they are being detected as the correct type.

**Comment by JtheBAB** [comment] 2021-06-22 18:43
Ahhh got it now. It was using the Intel GPU instead of my NVidia. After forcing it to use system wide the NVidia Card it came up. Do you have per chance a good controller binding?

**Comment by TstewDev** [comment] 2021-07-08 19:56
I had to go back and confirm the method I used but here is the best way of doing it.

Mapping Controllers for PyMOL in SteamVR:
1. Open the SteamVR menu and go to settings
2. Click "Show Advanced" in the bottom left
3. Select Controllers
4. Click "Show old binding UI"
5. Select "python" or "pythonw" or "pymol" (depends on how its opened I believe)
6. Click the edit icon under each trigger/button to an action

I recommend at least mapping the following:
- Grab to the inside paddles/triggers
- Menu to one of the button or triggers
- Laser to one of the triggers 

Once these are mapped, you can play around with the structure and then modify once you figure out what makes the most sense to you.

**Comment by TstewDev** [comment] 2021-07-08 19:58
I'm closing this issue but feel free to open it again if you have any more difficulties!

**Closed by TstewDev** 2021-07-08 19:58 UTC
