### ISSUE TITLE
Pymol fails after updating to Mac OS X Big Sur

### ISSUE THREAD

**Issue by ToyinAs** [schrodinger/pymol-open-source#162] opened 2021-01-22 19:06 UTC
This is the error I get. Both my prepaid license and free version of PyMOL no longer work. 

This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 2.0 or greater. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
  GL_VERSION:  2.1 INTEL-16.1.7
ERROR: CGOOptimizeToVBONotIndexed() glGenBuffers returns err=1286
ERROR: CGOOptimizeScreenTexturesAndPolygons() glGenBuffers returns err=1281

**Comment by speleo3** [comment] 2021-02-01 08:56
PyMOL runs without problems for us on Big Sur. Could there be anything special with your setup? Did you try to re-install PyMOL?

**Comment by AZapaBC** [comment] 2021-02-17 16:32
I've got the same problem, PyMOL doesn't run on BigSur, I re install PyMol and I still have:
 This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 2.0 or greater. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel(R) UHD Graphics 617
  GL_VERSION:  2.1 INTEL-16.1.10
ERROR: CGOOptimizeToVBONotIndexed() glGenBuffers returns err=1286
ERROR: CGOOptimizeScreenTexturesAndPolygons() glGenBuffers returns err=1286

**Comment by speleo3** [comment] 2021-02-18 08:25
Please include your PyMOL version in your next bug report. I guess that you're running MacPyMOL 1.8 or older, which is not supported anymore. Please upgrade to PyMOL 2.4.

**Comment by speleo3** [comment] 2021-04-09 13:06
Closing because the issue is fixed in PyMOL 2.4

**Closed by speleo3** 2021-04-09 13:06 UTC
