### ISSUE TITLE
Matrix: Warning: no convergence.. after 1000 iterations

### ISSUE THREAD

**Issue by sspleo** [schrodinger/pymol-open-source#145] opened 2020-11-05 05:22 UTC
Hi,

 I am trying to calculate RMSD scores of protein chain pairs by using 'super' and 'align' command in python.
 For the purpose of pairwise RMSD calculation, I first create n by n numpy matrix and assign the elementiwise RMSD value of eachpair into the matrix.

 By multiprocessing, the calculation in the beginning does not take much time for first millions of calculation. However, I get tons of message : 'Matrix: Warning: no convergence (0.00000010<xxxxxx.xxxxx after 1000 iterations).'
 Eventhough that was 2 by 2 matrix, it could take an hour to be done. By the way, same calculation takes a few seconds in PyMOL GUI program.

 Any help would be appreciated.

 Leo

**Comment by speleo3** [comment] 2020-12-10 08:58
Can you share a reproducible example? What script commands do you run?

**Comment by JarrettSJohnson** [comment] 2021-07-07 17:58
Closing this issue since the original poster hasn't responded in several months. If you have a reproduceable example, feel free to re-open.

**Closed by JarrettSJohnson** 2021-07-07 17:58 UTC
Labels: incomplete
