### ISSUE TITLE
Error about building model

### ISSUE THREAD

**Issue by hexa-tert** [schrodinger/pymol-open-source#252] opened 2022-08-24 23:14 UTC
When I try to build a protein model by clicking build>residue>Leucine, It shows codes below:

Traceback (most recent call last):
  File "E:\Pymol\pymol\lib\site-packages\pymol\_gui.py", line 193, in <lambda>
    ('command', lab, lambda v=val: cmd.editor.attach_amino_acid('pk1', v))
  File "E:\Pymol\pymol\lib\site-packages\pymol\editor.py", line 108, in attach_amino_acid
    bound_count = _self.count_atoms("bound_to " + selection)
  File "E:\Pymol\pymol\lib\site-packages\pymol\querying.py", line 1460, in count_atoms
    r = _cmd.select(_self._COb,"_count_tmp","("+str(selection)+")",1,int(state)-1,str(domain))
pymol.CmdException:  Error: Invalid selection name "pk1".
( bound_to pk1 )<--

I can't find anyone else has the same problem on google, could anyone help me figure this out?

**Comment by JarrettSJohnson** [comment] 2022-08-30 16:56
I can't reproduce on Open-Source but I can reproduce on the other versions. Can you confirm?

Also, `fab` command and using the builder panel GUI works for me on the incentive/EDU versions. Can you see if that works for you.

**Comment by hexa-tert** [comment] 2022-08-30 18:00
> I can't reproduce on Open-Source but I can reproduce on the other versions. Can you confirm?
> 
> Also, `fab` command and using the builder panel GUI works for me on the incentive/EDU versions. Can you see if that works for you.

I just downloaded the old version - pymol 2.5.2 and it works very well. My laptop had a win11 system, might have some crush with new version.

**Comment by JarrettSJohnson** [comment] 2022-08-30 18:03
Thanks for confirming. And just FYI, the download that exists on the pymol.org website is not the open source version. As such, I'll close this ticket and we'll resolve this issue accordingly with incentive version 2.5.5 in the upcoming weeks.

**Closed by JarrettSJohnson** 2022-08-30 18:03 UTC
