### ISSUE TITLE
macOS: running pymol through python session fails to launch and crashes the python session

### ISSUE THREAD

**Issue by bzoracler** [schrodinger/pymol-open-source#97] opened 2020-05-12 07:08 UTC
I'm trying to call pymol through a python session by

`import pymol`
`pymol.finish_launching()`

but it fails to launch and crashes the python session. Running pymol by calling the Python interpreter with `__init__.py` runs normally. The output message is:

```
 PyMOL(TM) Molecular Graphics System, Version 2.4.0a0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.
 Hit ESC anytime to toggle between text and graphics.
 Detected OpenGL version 2.1. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Apple Inc.
  GL_RENDERER: Apple Software Renderer
  GL_VERSION:  2.1 APPLE-14.0.16
2020-05-12 18:47:13.870 Python[20216:174122] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1349.91/Misc.subproj/NSUndoManager.m:363
2020-05-12 18:47:13.879 Python[20216:174122] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7d3532cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff9218548d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7d358042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff7eda0be0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fff7ed2b093 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 170
	5   AppKit                              0x00007fff7adb74ed -[NSApplication run] + 1200
	6   libqcocoa.dylib                     0x0000000115067013 qt_plugin_instance + 177507
	7   QtCore                              0x0000000113b14fef _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
	8   QtCore                              0x0000000113b1a182 _ZN16QCoreApplication4execEv + 130
	9   QtWidgets.so                        0x0000000114b6f762 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
	10  Python                              0x000000010ed9d64e _PyMethodDef_RawFastCallKeywords + 243
	11  Python                              0x000000010ed9cca4 _PyCFunction_FastCallKeywords + 44
	12  Python                              0x000000010ee313a2 call_function + 624
	13  Python                              0x000000010ee2a0a3 _PyEval_EvalFrameDefault + 4484
	14  Python                              0x000000010ed9d083 function_code_fastcall + 116
	15  Python                              0x000000010ee31412 call_function + 736
	16  Python                              0x000000010ee2a0a3 _PyEval_EvalFrameDefault + 4484
	17  Python                              0x000000010ee31bf6 _PyEval_EvalCodeWithName + 1683
	18  Python                              0x000000010ed9c8d2 _PyFunction_FastCallDict + 441
	19  Python                              0x000000010ee2a3cc _PyEval_EvalFrameDefault + 5293
	20  Python                              0x000000010ed9d083 function_code_fastcall + 116
	21  Python                              0x000000010ee31412 call_function + 736
	22  Python                              0x000000010ee2a08a _PyEval_EvalFrameDefault + 4459
	23  Python                              0x000000010ed9d083 function_code_fastcall + 116
	24  Python                              0x000000010ee31412 call_function + 736
	25  Python                              0x000000010ee2a08a _PyEval_EvalFrameDefault + 4459
	26  Python                              0x000000010ed9d083 function_code_fastcall + 116
	27  Python                              0x000000010ed9da65 _PyObject_Call_Prepend + 150
	28  Python                              0x000000010ed9cdb2 PyObject_Call + 136
	29  Python                              0x000000010ee97955 t_bootstrap + 71
	30  Python                              0x000000010ee5f4f6 pythread_wrapper + 25
	31  libsystem_pthread.dylib             0x00007fff92cd893b _pthread_body + 180
	32  libsystem_pthread.dylib             0x00007fff92cd8887 _pthread_body + 0
	33  libsystem_pthread.dylib             0x00007fff92cd808d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by speleo3** [comment] 2020-05-12 07:57
`pymol.finish_launching()` is not supported on macOS.

Duplicate of #28

**Closed by speleo3** 2020-05-12 07:57 UTC
Labels: duplicate
