### ISSUE TITLE
Unable to re-open PyMOL 3 session file

### ISSUE THREAD

**Issue by ccr1752** [schrodinger/pymol-open-source#409] opened 2024-11-29 12:31 UTC
**Issue Description**
Hi,
I’m encountering a crash when reopening a saved PyMOL 3 session file. The session included a movie I was working on. When I attempt to open the .pse file, PyMOL starts loading but immediately closes (crashes).

**Steps to Reproduce**
1. Create a movie in PyMOL 3 (with keyframes, if applicable).
2. Save the session as a .pse file.
3. Close PyMOL.
4. Could you try to reopen the saved session file?

**Additional Information**
PyMOL Version: 3.1.1 
Operating System: Windows 11
The .pse file size is approximately 4,042 KB

Thanks, any help would be appreciated.

**Comment by TstewDev** [comment] 2024-12-02 22:25
Hello @ccr1752,

I was able to reproduce the crash on my Windows 11 laptop with PyMOL 3.1.1. This is definitely not present on intel mac but I will check other operating systems tomorrow. In the meantime, you should be able to download 3.0.4 from the "For previous versions, see here." link on the [download page](https://pymol.org/#download) (not linking directly since I believe this link can change). 3.0.4 appears to be the latest version without this issue and the files created with 3.0.4 open without any trouble in 3.1.1, so there's no concern about losing your work when switching back to a newer version.

We plan on releasing 3.1.2 this week, so the fix for this will likely have to wait for 3.1.3, but it will be a high priority given the severity.

I'm going to close this Github issue since this specific to features found in Incentive PyMOL but not in open source. I will, however, create an internal ticket to make sure this gets fixed. If you need any additional support or assistance, please contact help@schrodinger.com.

Thanks for finding and reporting this!

**Closed by TstewDev** 2024-12-02 22:25 UTC
